### ISSUE TITLE
how to use in PHP

### ISSUE THREAD

**Issue by coinhosting** [foril/splitsms#1]
hi,

how to use UHD in php for match DLR for all parts we use kannel sms gateway.

thanks

**Comment by foril** [comment]
This a Go library, it's better for you to split directly in php with your code.

Look at this library by example https://github.com/messente/sms-length-calculator

The better method for match one DLR with sended SMS is to split your message before to send to smsbox, like that you can pass your internal ID for each part and get your internal ID on the dlr-url from the smsbox.
